site_name: dj_settings
site_description: Project settings the UNIX way
site_author: Stephanos Kuma

repo_url: https://github.com/spapanik/dj_settings
repo_name: spapanik/dj_settings

nav:
  - Home: README.md
  - Getting Started:
      - Installation: installation.md
      - Quick Start: usage/index.md
  - User Guide:
      - Configuration Parsers: usage/parsers.md
      - Settings Classes: usage/decorator.md
  - Reference:
      - API Overview: usage/index.md#public-api
      - ConfigParser: usage/parsers.md#configparser-class
      - get_setting: usage/parsers.md#get_setting-function
      - settings_class: usage/decorator.md#the-settings_class-decorator
      - config_value: usage/decorator.md#the-config_value-helper
  - About:
      - Changelog: CHANGELOG.md
      - License: LICENSE.md
      - Code of Conduct: CODE_OF_CONDUCT.md

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets

theme:
  name: material

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - search
    - search.suggest
    - search.share
